name: Flutter CI

on:
  push:
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      # Build debug APK to ensure it compiles; release AAB will be later
      - run: flutter build apk --debug
